pipeline:
  create_cluster:
    image: banzaicloud/ci-pipeline-client:latest
    cluster:
      name: martonseregprw1
      location: us-west-2
      cloud: amazon
      secretId: 1d6b1aae055184a903e51c2d417c4e9e13e6e6249f0ec503f5a1b7d0c6ac095d
      secretName: ""
      profileName: ""
      postHooks:
        InstallLogging:
          bucketName: marton-kops-state-store
          region: us-east-1
          secretId: 1d6b1aae055184a903e51c2d417c4e9e13e6e6249f0ec503f5a1b7d0c6ac095d
        InstallMonitoring: {}
      properties:
        eks:
          nodePools:
            pool1:
              instanceType: c5.xlarge
              spotPrice: "0"
              autoscaling: true
              minCount: 1
              maxCount: 2
              count: 1
              image: ""
            pool2:
              instanceType: c4.xlarge
              spotPrice: "0.2"
              autoscaling: true
              minCount: 1
              maxCount: 2
              count: 1
              image: ""
            pool3:
              instanceType: c5.xlarge
              spotPrice: "0.17"
              autoscaling: true
              minCount: 1
              maxCount: 2
              count: 1
              image: ""
            system:
              instanceType: t2.medium
              spotPrice: ""
              autoscaling: true
              minCount: 1
              maxCount: 2
              count: 1
              image: ""
    action: EnsureCluster
  test:
    image: node:10-slim
    commands:
    - npm ci
  build_container:
    dockerfile: Dockerfile
    image: plugins/docker
    repo: '{{ .DRONE_REPO }}'
    secretFrom:
      DOCKER_PASSWORD:
        keyRef: password
        name: spotguide-nodejs-mongodb-docker-hub
      DOCKER_USERNAME:
        keyRef: username
        name: spotguide-nodejs-mongodb-docker-hub
    tags: '{{ trunc 7 .DRONE_COMMIT_SHA }}'
  package_application:
    when:
      branch:
        include:
        - master
    image: lachlanevenson/k8s-helm:latest
    commands:
    - helm init -c
    - helm repo add banzaicloud-stable http://kubernetes-charts.banzaicloud.com/branch/master
    - helm package -u ./.banzaicloud/charts/spotguide-nodejs-mongodb
  install_mongodb_user_secret:
    action: InstallSecret
    cluster_secret:
      merge: true
      name: '{{ .DRONE_REPO }}-mongodb'
      namespace: default
      sourceSecretName: spotguide-nodejs-mongodb-mongodb
      spec:
      - name: mongodb-username
        source: username
      - name: mongodb-password
        source: password
    image: banzaicloud/ci-pipeline-client:latest
    when:
      branch:
        include:
        - master
  install_mongodb_root_secret:
    action: InstallSecret
    cluster_secret:
      merge: true
      name: '{{ .DRONE_REPO }}-mongodb'
      namespace: default
      sourceSecretName: spotguide-nodejs-mongodb-mongodb-root
      spec:
      - name: mongodb-root-password
        source: password
    image: banzaicloud/ci-pipeline-client:latest
    when:
      branch:
        include:
        - master
  deploy_application:
    action: EnsureDeployment
    deployment:
      name: ./spotguide-nodejs-mongodb-1.0.0.tgz
      releaseName: '{{ .DRONE_REPO_NAME }}'
      reuseValues: true
      values:
        application:
          deployment:
            image:
              pullPolicy: Always
              repository: '{{ .DRONE_REPO }}'
              tag: '{{ trunc 7 .DRONE_COMMIT_SHA }}'
            resources:
              limits:
                cpu: 1000m
                memory: 512Mi
              requests:
                cpu: 500m
                memory: 256Mi
          ingress:
            hosts:
            - app.{{ .DRONE_REPO_NAME }}.{{ .CLUSTER_NAME }}.{{ .ORG_NAME }}.{{ .DOMAIN_NAME }}
        mongodb:
          existingSecret: '{{ .DRONE_REPO }}-mongodb'
          mongodbDatabase: node-application
          mongodbUsername: marton
    image: banzaicloud/ci-pipeline-client:latest
    when:
      branch:
        include:
        - master
